name: PluginManagerWeb
main: fr.matissead.pluginmanagerweb.PluginManagerWeb
version: 0.1.0
api-version: 1.20
description: |
  Un plugin optionnel pour gérer et superviser les autres plugins de MatisseAD via un tableau de bord web embarqué.
authors:
  - MatisseAD
  - Copilot
website: https://github.com/MatisseAD

# Commandes potentielles définies par le plugin
commands:
  pluginmanager:
    description: Commande principale pour PluginManagerWeb.
    usage: /<command> help
    permission: pluginmanagerweb.command

# Permissions par défaut
permissions:
  pluginmanagerweb.command:
    description: Permission pour utiliser la commande principale.
    default: op
